# Configure TravisCI (https://travis-ci.org) tests
language: generic

# Test on both Linux and OSX
os:
  - linux
  - osx

# The following lines are needed by Codecov
sudo: required
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

# Make sure the home directory is set to 
# be the TravisCI project directory
env:
  GBPENV_TEST=1
  HOME=${TRAVIS_BUILD_DIR}

# Perform environment install
before_script: |
  echo dir=${TRAVIS_BUILD_DIR}
  ls
  make -f .gbpEnv/Makefile

# Run tests (via Makefile) using assert.sh
script: |
  make -f .test/Makefile tests

# Add the following lines to generate Codecov report
after_success: |
  make -f .test/Makefile kcov
