# Configure TravisCI (https://travis-ci.org) tests
language: bash

# Test on both Linux and OSX
os:
  - linux
  - osx

# The following lines are needed by Codecov
sudo: required
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

# Make sure the home directory is set to 
# be the TravisCI project directory
env:
  HOME=${TRAVIS_BUILD_DIR}

# All the tests will be run by this Makefile
#    using assert.sh
script: |
    make -f .test/Makefile test

# Add the following lines to generate Codecov report
after_success: |
    make -f .test/Makefile kcov_bash

