# Configure TravisCI (https://travis-ci.org) tests
language: generic

# Test on both Linux and OSX
matrix:
    include:
        - os: linux
        - os: osx
          osx_image: xcode11

# Install build and test dependancies
sudo: required
addons:
  apt:
    packages:
      # Needed to build Stow documentation
      - texlive-latex-recommended
      - texlive-fonts-recommended
      - texinfo
  homebrew:
    packages:
    casks:
      # Needed to build Stow documentation
      - basictex
    #update: true

# Make sure the home directory is set to 
# be the TravisCI project directory
env:
  GBPENV_TEST=1
  HOME=${TRAVIS_BUILD_DIR}/../
  GBP_HOME=${TRAVIS_BUILD_DIR}/../

# Perform environment install
# * n.b.: We are in the repo dir at this point *
before_script: |
  # Make sure 'tex' is in the path for building the Stow documentation on OSX
  if [ $TRAVIS_OS_NAME = osx ]; then export PATH=/Library/TeX/texbin/:$PATH; fi
  # Perform install of packages
  cd ${TRAVIS_BUILD_DIR}/.. 
  make -f .gbpEnv/Makefile
  ls .gbpEnv/stow
  find . --name stow.log --exec cat {} \;

# Run tests (via Makefile) using assert.sh
script: |
  cd ${TRAVIS_BUILD_DIR}/.. 
  make -f .test/Makefile tests

# Add the following lines to generate Codecov report
after_success: |
  cd ${TRAVIS_BUILD_DIR}/.. 
  make -f .test/Makefile kcov
