# Configure TravisCI (https://travis-ci.org) tests
language: generic

# Test on both Linux and OSX
# Disabled OSX builds because I was going crazy getting the OSX build of Stow to return correctly.
# It seems to build right but returns an error, which I can not reproduce locally:
#
# > Output written on stow.pdf (40 pages, 274687 bytes).
# > Transcript written on stow.log.
# > make: *** [stow-build] Error 2
# > The command "# Make sure 'tex' is in the path for building the Stow documentation on OSX
# >   if [ $TRAVIS_OS_NAME = osx ]; then export PATH=/Library/TeX/texbin/:$PATH; fi
# >   # Perform install of packages
# >   cd ${TRAVIS_BUILD_DIR}/.. 
# >   make -f .gbpEnv/Makefile
# >   " failed and exited with 2 during .
# > Your build has been stopped.
#
matrix:
    include:
        - os: linux
#        - os: osx
#          osx_image: xcode11

# Install build and test dependancies
sudo: required
addons:
  apt:
    packages:
      # Needed to build Stow documentation
      - texlive-latex-recommended
      - texlive-fonts-recommended
      - texinfo
  homebrew:
    packages:
    casks:
      # Needed to build Stow documentation
      - mactex
    #update: true

# Make sure the home directory is set to 
# be the TravisCI project directory
env:
  GBPENV_TEST=1
  HOME=${TRAVIS_BUILD_DIR}/../
  GBP_HOME=${TRAVIS_BUILD_DIR}/../

# Perform environment install
# * n.b.: We are in the repo dir at this point *
before_script: |
  # Make sure 'tex' is in the path for building the Stow documentation on OSX
  if [ $TRAVIS_OS_NAME = osx ]; then export PATH=/Library/TeX/texbin/:$PATH; fi
  # Perform install of packages
  cd ${TRAVIS_BUILD_DIR}/.. 
  make -f .gbpEnv/Makefile

# Run tests (via Makefile) using assert.sh
script: |
  cd ${TRAVIS_BUILD_DIR}/.. 
  make -f .test/Makefile tests

# Add the following lines to generate Codecov report
after_success: |
  cd ${TRAVIS_BUILD_DIR}/.. 
  make -f .test/Makefile kcov
