TS_SEARCH_PATHS=(~/mycode:1 ~/.gbpEnv ~/3rd_Party ~/Projects:1 ~/Projects/ADACS/MAP)
TS_EXTRA_SEARCH_PATHS=(~/dotfiles/ /work/gh/github.com/qmacro)
TS_MAX_DEPTH=0
TS_LOG=file
TS_LOG_FILE=/tmp/tmux-sessionizer/log.txt
