# use :# to indicate the depth to search.
#   depth == 0, just use the given path
#   depth <  0, include all paths to given depth
#   depth >  0, only include roots of git repos to given depth
TS_SEARCH_PATHS=(~/my_code/:1 ~/.gbpEnv:0 ~/3rd_Party:0 ~/Projects/:-1 ~/Projects/ADACS/MAP:0)
TS_EXTRA_SEARCH_PATHS=( )
TS_MAX_DEPTH=0
TS_LOG=file
TS_LOG_FILE=/tmp/tmux-sessionizer/log.txt
